#ifndef MESSAGEKINDS_H_
#define MESSAGEKINDS_H_

enum MessageKinds
{
    INITIAL_BROADCAST_MESSAGE,
    SELF_MESSAGE,
    SELF_ACK_MESSAGE,
    SELF_REPLY_MESSAGE,
    REPLY_MESSAGE,
    ACK_REPLY_MESSAGE,
    SELF_BROADCAST_MESSAGE,
    RUBBISH_MESSAGE
};

#endif
